filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

filetype plugin indent on

set softtabstop=4
set tabstop=4
set shiftwidth=4
set expandtab

nnoremap <SPACE> <Nop>
let mapleader=" "

function! Preserve(command)
    let winview = winsaveview()
    execute a:command
    call winrestview(winview)
endfunction

nmap <leader>$ :call Preserve("%s/\\s\\+$//e")<CR>
nmap <leader>= :call Preserve("normal gg=G")<CR>
